import { getInitials } from "@/lib/utils";
import { Author } from "@/types";

export interface QuestionChoice {
  id: string;
  text: string;
  isCorrect: boolean;
}

export interface Question {
  id: string;
  type: 'single-choice' | 'multiple-choice' | 'descriptive';
  text: string;
  choices: QuestionChoice[];
  score: number;
  timeLimit: number;
  required: boolean;
}

export interface Section {
  id: string;
  title: string;
  description?: string;
  questions: Question[];
}

export interface Course {
  id: string;
  title: string;
  description: string;
  sections: Section[];
  isPublished: boolean;
  isMyCourse: boolean;
  author: Author;
}

const placeholderImageURL = process.env.NEXT_PUBLIC_DEFAULT_AVATAR_URL || "https://picsum.photos/300/200?random=";


export const courseQuestionData: Course[] = [
  {
    id: "course1",
    title: "Introduction to General Knowledge",
    description: "Embark on a journey to broaden your understanding of the world with this comprehensive course designed to enhance your general awareness. Explore diverse topics including world geography, historical events, cultural diversity, science, technology, arts, and literature. This course offers engaging quizzes and in-depth questions to test and expand your knowledge across multiple disciplines. Perfect for learners seeking to develop a well-rounded perspective, it covers essential facts, historical milestones, cultural traditions, and scientific principles to foster intellectual curiosity and informed decision-making in an interconnected global society.",
    isPublished: false,
    isMyCourse: true,
    author: {
          name: "Sufain Huzaif",
          avatar: `${placeholderImageURL}1`,
          initials: getInitials("Sufain Huzaif"),
        },
    sections: [
      {
        id: "sec1-1",
        title: "World Geography",
        description: "Explore the physical and human geography of the world.",
        questions: [
          {
            id: "q1-1-1",
            type: "single-choice",
            text: "What is the largest continent by land area?",
            choices: [
              { id: "c1", text: "Asia", isCorrect: true },
              { id: "c2", text: "Africa", isCorrect: false },
              { id: "c3", text: "Australia", isCorrect: false },
              { id: "c4", text: "Antarctica", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-1-2",
            type: "multiple-choice",
            text: "Which countries are in Scandinavia?",
            choices: [
              { id: "c1", text: "Norway", isCorrect: true },
              { id: "c2", text: "Finland", isCorrect: false },
              { id: "c3", text: "Sweden", isCorrect: true },
              { id: "c4", text: "Denmark", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-1-3",
            type: "descriptive",
            text: "Explain the formation of the Grand Canyon.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-1-4",
            type: "single-choice",
            text: "Which ocean is the largest?",
            choices: [
              { id: "c1", text: "Pacific Ocean", isCorrect: true },
              { id: "c2", text: "Atlantic Ocean", isCorrect: false },
              { id: "c3", text: "Indian Ocean", isCorrect: false },
              { id: "c4", text: "Arctic Ocean", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-1-5",
            type: "multiple-choice",
            text: "Which of these are major world rivers?",
            choices: [
              { id: "c1", text: "Nile", isCorrect: true },
              { id: "c2", text: "Thames", isCorrect: false },
              { id: "c3", text: "Amazon", isCorrect: true },
              { id: "c4", text: "Yangtze", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-1-6",
            type: "descriptive",
            text: "Describe the impact of urbanization on global landscapes.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-1-7",
            type: "single-choice",
            text: "What is the capital of Japan?",
            choices: [
              { id: "c1", text: "Tokyo", isCorrect: true },
              { id: "c2", text: "Osaka", isCorrect: false },
              { id: "c3", text: "Kyoto", isCorrect: false },
              { id: "c4", text: "Hiroshima", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-1-8",
            type: "multiple-choice",
            text: "Which countries are part of the Sahara Desert?",
            choices: [
              { id: "c1", text: "Egypt", isCorrect: true },
              { id: "c2", text: "Brazil", isCorrect: false },
              { id: "c3", text: "Algeria", isCorrect: true },
              { id: "c4", text: "Morocco", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-1-9",
            type: "descriptive",
            text: "What are the major factors affecting climate zones?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-1-10",
            type: "single-choice",
            text: "What is the capital of Brazil?",
            choices: [
              { id: "c1", text: "Brasília", isCorrect: true },
              { id: "c2", text: "Rio de Janeiro", isCorrect: false },
              { id: "c3", text: "São Paulo", isCorrect: false },
              { id: "c4", text: "Salvador", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec1-2",
        title: "Historical Events",
        description: "Learn about significant events that shaped human history.",
        questions: [
          {
            id: "q1-2-1",
            type: "single-choice",
            text: "Who discovered America in 1492?",
            choices: [
              { id: "c1", text: "Christopher Columbus", isCorrect: true },
              { id: "c2", text: "Vasco da Gama", isCorrect: false },
              { id: "c3", text: "Ferdinand Magellan", isCorrect: false },
              { id: "c4", text: "Marco Polo", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-2-2",
            type: "multiple-choice",
            text: "Which events occurred during the Renaissance?",
            choices: [
              { id: "c1", text: "Mona Lisa painted", isCorrect: true },
              { id: "c2", text: "Moon landing", isCorrect: false },
              { id: "c3", text: "Gutenberg’s printing press", isCorrect: true },
              { id: "c4", text: "Fall of Constantinople", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-2-3",
            type: "descriptive",
            text: "Explain the causes of World War I.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-2-4",
            type: "single-choice",
            text: "In which year did the American Civil War end?",
            choices: [
              { id: "c1", text: "1865", isCorrect: true },
              { id: "c2", text: "1861", isCorrect: false },
              { id: "c3", text: "1870", isCorrect: false },
              { id: "c4", text: "1859", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-2-5",
            type: "multiple-choice",
            text: "Which leaders were involved in World War II?",
            choices: [
              { id: "c1", text: "Winston Churchill", isCorrect: true },
              { id: "c2", text: "Napoleon Bonaparte", isCorrect: false },
              { id: "c3", text: "Adolf Hitler", isCorrect: true },
              { id: "c4", text: "Franklin Roosevelt", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-2-6",
            type: "descriptive",
            text: "Describe the impact of the Industrial Revolution on society.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-2-7",
            type: "single-choice",
            text: "Who was the first emperor of the Roman Empire?",
            choices: [
              { id: "c1", text: "Augustus", isCorrect: true },
              { id: "c2", text: "Julius Caesar", isCorrect: false },
              { id: "c3", text: "Nero", isCorrect: false },
              { id: "c4", text: "Constantine", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-2-8",
            type: "multiple-choice",
            text: "Which ancient civilizations built pyramids?",
            choices: [
              { id: "c1", text: "Egyptian", isCorrect: true },
              { id: "c2", text: "Greek", isCorrect: false },
              { id: "c3", text: "Mayan", isCorrect: true },
              { id: "c4", text: "Roman", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-2-9",
            type: "descriptive",
            text: "What was the significance of the Magna Carta?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-2-10",
            type: "single-choice",
            text: "Which year marked the fall of the Berlin Wall?",
            choices: [
              { id: "c1", text: "1989", isCorrect: true },
              { id: "c2", text: "1991", isCorrect: false },
              { id: "c3", text: "1985", isCorrect: false },
              { id: "c4", text: "1979", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-2-11",
            type: "multiple-choice",
            text: "Which of these were part of the Cold War?",
            choices: [
              { id: "c1", text: "Cuban Missile Crisis", isCorrect: true },
              { id: "c2", text: "French Revolution", isCorrect: false },
              { id: "c3", text: "Space Race", isCorrect: true },
              { id: "c4", text: "Vietnam War", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-2-12",
            type: "descriptive",
            text: "Explain the role of the United Nations in global peace.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-2-13",
            type: "single-choice",
            text: "Who led the Indian independence movement?",
            choices: [
              { id: "c1", text: "Mahatma Gandhi", isCorrect: true },
              { id: "c2", text: "Jawaharlal Nehru", isCorrect: false },
              { id: "c3", text: "Subhas Chandra Bose", isCorrect: false },
              { id: "c4", text: "Bhagat Singh", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-2-14",
            type: "multiple-choice",
            text: "Which empires ruled in the Middle Ages?",
            choices: [
              { id: "c1", text: "Byzantine Empire", isCorrect: true },
              { id: "c2", text: "Mongol Empire", isCorrect: true },
              { id: "c3", text: "British Empire", isCorrect: false },
              { id: "c4", text: "Holy Roman Empire", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-2-15",
            type: "descriptive",
            text: "Describe the impact of the Black Death on Europe.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
        ],
      },
      {
        id: "sec1-3",
        title: "Cultural Diversity",
        description: "Understand the diverse cultures and traditions around the globe.",
        questions: [
          {
            id: "q1-3-1",
            type: "single-choice",
            text: "What is the traditional Japanese tea ceremony called?",
            choices: [
              { id: "c1", text: "Chanoyu", isCorrect: true },
              { id: "c2", text: "Sado", isCorrect: false },
              { id: "c3", text: "Kimono", isCorrect: false },
              { id: "c4", text: "Origami", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-3-2",
            type: "multiple-choice",
            text: "Which festivals are celebrated in India?",
            choices: [
              { id: "c1", text: "Diwali", isCorrect: true },
              { id: "c2", text: "Christmas", isCorrect: false },
              { id: "c3", text: "Holi", isCorrect: true },
              { id: "c4", text: "Eid", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-3-3",
            type: "descriptive",
            text: "Explain the significance of the Chinese New Year.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-3-4",
            type: "single-choice",
            text: "What is the traditional dance of Spain?",
            choices: [
              { id: "c1", text: "Flamenco", isCorrect: true },
              { id: "c2", text: "Salsa", isCorrect: false },
              { id: "c3", text: "Tango", isCorrect: false },
              { id: "c4", text: "Ballet", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-3-5",
            type: "multiple-choice",
            text: "Which instruments are used in African music?",
            choices: [
              { id: "c1", text: "Djembe", isCorrect: true },
              { id: "c2", text: "Sitar", isCorrect: false },
              { id: "c3", text: "Kora", isCorrect: true },
              { id: "c4", text: "Balalaika", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-3-6",
            type: "descriptive",
            text: "Describe the role of storytelling in Indigenous cultures.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-3-7",
            type: "single-choice",
            text: "What is the national flower of Mexico?",
            choices: [
              { id: "c1", text: "Dahlia", isCorrect: true },
              { id: "c2", text: "Rose", isCorrect: false },
              { id: "c3", text: "Tulip", isCorrect: false },
              { id: "c4", text: "Lotus", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-3-8",
            type: "multiple-choice",
            text: "Which foods are traditional in Italy?",
            choices: [
              { id: "c1", text: "Pizza", isCorrect: true },
              { id: "c2", text: "Sushi", isCorrect: false },
              { id: "c3", text: "Pasta", isCorrect: true },
              { id: "c4", text: "Tacos", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-3-9",
            type: "descriptive",
            text: "What is the cultural importance of the Maasai tribe’s beadwork?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-3-10",
            type: "single-choice",
            text: "What is the traditional clothing of Scotland?",
            choices: [
              { id: "c1", text: "Kilt", isCorrect: true },
              { id: "c2", text: "Sari", isCorrect: false },
              { id: "c3", text: "Kimono", isCorrect: false },
              { id: "c4", text: "Sombrero", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-3-11",
            type: "multiple-choice",
            text: "Which religions originated in the Middle East?",
            choices: [
              { id: "c1", text: "Islam", isCorrect: true },
              { id: "c2", text: "Buddhism", isCorrect: false },
              { id: "c3", text: "Judaism", isCorrect: true },
              { id: "c4", text: "Christianity", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-3-12",
            type: "descriptive",
            text: "Explain the significance of Aboriginal Dreamtime stories.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
        ],
      },
      {
        id: "sec1-4",
        title: "Science and Technology",
        description: "Discover key scientific concepts and technological advancements.",
        questions: [
          {
            id: "q1-4-1",
            type: "single-choice",
            text: "What gas is most abundant in Earth’s atmosphere?",
            choices: [
              { id: "c1", text: "Nitrogen", isCorrect: true },
              { id: "c2", text: "Oxygen", isCorrect: false },
              { id: "c3", text: "Carbon Dioxide", isCorrect: false },
              { id: "c4", text: "Argon", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-4-2",
            type: "multiple-choice",
            text: "Which of these are renewable energy sources?",
            choices: [
              { id: "c1", text: "Solar", isCorrect: true },
              { id: "c2", text: "Coal", isCorrect: false },
              { id: "c3", text: "Wind", isCorrect: true },
              { id: "c4", text: "Hydropower", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-4-3",
            type: "descriptive",
            text: "Explain the process of photosynthesis.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-4-4",
            type: "single-choice",
            text: "Who invented the light bulb?",
            choices: [
              { id: "c1", text: "Thomas Edison", isCorrect: true },
              { id: "c2", text: "Nikola Tesla", isCorrect: false },
              { id: "c3", text: "Alexander Bell", isCorrect: false },
              { id: "c4", text: "Guglielmo Marconi", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-4-5",
            type: "multiple-choice",
            text: "Which are types of electromagnetic waves?",
            choices: [
              { id: "c1", text: "Radio waves", isCorrect: true },
              { id: "c2", text: "Sound waves", isCorrect: false },
              { id: "c3", text: "X-rays", isCorrect: true },
              { id: "c4", text: "Gamma rays", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-4-6",
            type: "descriptive",
            text: "Describe the importance of the internet in modern society.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-4-7",
            type: "single-choice",
            text: "What is the chemical symbol for water?",
            choices: [
              { id: "c1", text: "H2O", isCorrect: true },
              { id: "c2", text: "CO2", isCorrect: false },
              { id: "c3", text: "O2", isCorrect: false },
              { id: "c4", text: "N2", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-4-8",
            type: "multiple-choice",
            text: "Which scientists contributed to modern physics?",
            choices: [
              { id: "c1", text: "Albert Einstein", isCorrect: true },
              { id: "c2", text: "Isaac Newton", isCorrect: true },
              { id: "c3", text: "William Shakespeare", isCorrect: false },
              { id: "c4", text: "Stephen Hawking", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-4-9",
            type: "descriptive",
            text: "What are the benefits of space exploration?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-4-10",
            type: "single-choice",
            text: "What is the primary source of energy for Earth?",
            choices: [
              { id: "c1", text: "Sun", isCorrect: true },
              { id: "c2", text: "Moon", isCorrect: false },
              { id: "c3", text: "Geothermal", isCorrect: false },
              { id: "c4", text: "Fossil fuels", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec1-5",
        title: "Arts and Literature",
        description: "Explore the world of art, literature, and creative expression.",
        questions: [
          {
            id: "q1-5-1",
            type: "single-choice",
            text: "Who painted the Sistine Chapel ceiling?",
            choices: [
              { id: "c1", text: "Michelangelo", isCorrect: true },
              { id: "c2", text: "Leonardo da Vinci", isCorrect: false },
              { id: "c3", text: "Raphael", isCorrect: false },
              { id: "c4", text: "Donatello", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-5-2",
            type: "multiple-choice",
            text: "Which of these are novels by Jane Austen?",
            choices: [
              { id: "c1", text: "Pride and Prejudice", isCorrect: true },
              { id: "c2", text: "Wuthering Heights", isCorrect: false },
              { id: "c3", text: "Sense and Sensibility", isCorrect: true },
              { id: "c4", text: "Emma", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-5-3",
            type: "descriptive",
            text: "Explain the characteristics of Impressionism in art.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-5-4",
            type: "single-choice",
            text: "Who wrote 'Hamlet'?",
            choices: [
              { id: "c1", text: "William Shakespeare", isCorrect: true },
              { id: "c2", text: "Christopher Marlowe", isCorrect: false },
              { id: "c3", text: "John Milton", isCorrect: false },
              { id: "c4", text: "Geoffrey Chaucer", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-5-5",
            type: "multiple-choice",
            text: "Which are musical genres?",
            choices: [
              { id: "c1", text: "Jazz", isCorrect: true },
              { id: "c2", text: "Baroque", isCorrect: true },
              { id: "c3", text: "Impressionism", isCorrect: false },
              { id: "c4", text: "Blues", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-5-6",
            type: "descriptive",
            text: "Describe the impact of the Romantic era on literature.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-5-7",
            type: "single-choice",
            text: "What is the name of Van Gogh’s famous painting?",
            choices: [
              { id: "c1", text: "Starry Night", isCorrect: true },
              { id: "c2", text: "The Scream", isCorrect: false },
              { id: "c3", text: "Guernica", isCorrect: false },
              { id: "c4", text: "Water Lilies", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-5-8",
            type: "multiple-choice",
            text: "Which artists are associated with Cubism?",
            choices: [
              { id: "c1", text: "Pablo Picasso", isCorrect: true },
              { id: "c2", text: "Claude Monet", isCorrect: false },
              { id: "c3", text: "Georges Braque", isCorrect: true },
              { id: "c4", text: "Henri Matisse", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q1-5-9",
            type: "descriptive",
            text: "What is the significance of Greek mythology in literature?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q1-5-10",
            type: "single-choice",
            text: "Who composed Symphony No. 5?",
            choices: [
              { id: "c1", text: "Ludwig van Beethoven", isCorrect: true },
              { id: "c2", text: "Mozart", isCorrect: false },
              { id: "c3", text: "Bach", isCorrect: false },
              { id: "c4", text: "Tchaikovsky", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q1-5-11",
            type: "multiple-choice",
            text: "Which are film genres?",
            choices: [
              { id: "c1", text: "Drama", isCorrect: true },
              { id: "c2", text: "Sci-Fi", isCorrect: true },
              { id: "c3", text: "Poetry", isCorrect: false },
              { id: "c4", text: "Thriller", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
        ],
      },
    ],
  },
  {
    id: "course2",
    title: "Science Fundamentals",
    description: "Dive into the fascinating world of science with this comprehensive course covering the essentials of physics, chemistry, and biology. Explore fundamental concepts such as motion, forces, atomic structure, chemical reactions, and the principles of life. Through engaging quizzes and thought-provoking questions, learners will gain a solid understanding of scientific principles that govern the natural world. This course delves into topics like energy conservation, the structure of matter, ecosystems, and the scientific method, fostering critical thinking and a deeper appreciation for the interconnectedness of physical and biological systems in our universe.",
    isPublished: true,
    isMyCourse: false,
    author: {
              name: "James P. Chandra",
              avatar: `${placeholderImageURL}James_P_Chandra`,
              initials: getInitials("James P. Chandra"),
            },
    sections: [
      {
        id: "sec2-1",
        title: "Physics Basics",
        description: "Understand the fundamental principles of physics.",
        questions: [
          {
            id: "q2-1-1",
            type: "single-choice",
            text: "What is the unit of force?",
            choices: [
              { id: "c1", text: "Newton", isCorrect: true },
              { id: "c2", text: "Joule", isCorrect: false },
              { id: "c3", text: "Watt", isCorrect: false },
              { id: "c4", text: "Pascal", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-1-2",
            type: "multiple-choice",
            text: "Which of these are fundamental forces?",
            choices: [
              { id: "c1", text: "Gravity", isCorrect: true },
              { id: "c2", text: "Friction", isCorrect: false },
              { id: "c3", text: "Electromagnetic", isCorrect: true },
              { id: "c4", text: "Strong nuclear", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-1-3",
            type: "descriptive",
            text: "Explain Newton’s First Law of Motion.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-1-4",
            type: "single-choice",
            text: "What is the speed of light in a vacuum?",
            choices: [
              { id: "c1", text: "3 x 10^8 m/s", isCorrect: true },
              { id: "c2", text: "3 x 10^6 m/s", isCorrect: false },
              { id: "c3", text: "3 x 10^10 m/s", isCorrect: false },
              { id: "c4", text: "3 x 10^4 m/s", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-1-5",
            type: "multiple-choice",
            text: "Which are units of energy?",
            choices: [
              { id: "c1", text: "Joule", isCorrect: true },
              { id: "c2", text: "Newton", isCorrect: false },
              { id: "c3", text: "Watt", isCorrect: false },
              { id: "c4", text: "Calorie", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-1-6",
            type: "descriptive",
            text: "Describe the concept of relativity.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-1-7",
            type: "single-choice",
            text: "What is the unit of electric charge?",
            choices: [
              { id: "c1", text: "Coulomb", isCorrect: true },
              { id: "c2", text: "Ampere", isCorrect: false },
              { id: "c3", text: "Volt", isCorrect: false },
              { id: "c4", text: "Ohm", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-1-8",
            type: "multiple-choice",
            text: "Which scientists contributed to quantum mechanics?",
            choices: [
              { id: "c1", text: "Max Planck", isCorrect: true },
              { id: "c2", text: "Galileo Galilei", isCorrect: false },
              { id: "c3", text: "Werner Heisenberg", isCorrect: true },
              { id: "c4", text: "Niels Bohr", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-1-9",
            type: "descriptive",
            text: "What is the significance of the conservation of energy?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-1-10",
            type: "single-choice",
            text: "What is the formula for kinetic energy?",
            choices: [
              { id: "c1", text: "1/2 mv^2", isCorrect: true },
              { id: "c2", text: "mv", isCorrect: false },
              { id: "c3", text: "mgh", isCorrect: false },
              { id: "c4", text: "F=ma", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-1-11",
            type: "multiple-choice",
            text: "Which are properties of waves?",
            choices: [
              { id: "c1", text: "Wavelength", isCorrect: true },
              { id: "c2", text: "Mass", isCorrect: false },
              { id: "c3", text: "Frequency", isCorrect: true },
              { id: "c4", text: "Amplitude", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-1-12",
            type: "descriptive",
            text: "Explain the Doppler effect.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
        ],
      },
      {
        id: "sec2-2",
        title: "Chemistry Fundamentals",
        description: "Learn about the building blocks of matter.",
        questions: [
          {
            id: "q2-2-1",
            type: "single-choice",
            text: "What is the atomic number of carbon?",
            choices: [
              { id: "c1", text: "6", isCorrect: true },
              { id: "c2", text: "12", isCorrect: false },
              { id: "c3", text: "8", isCorrect: false },
              { id: "c4", text: "14", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-2-2",
            type: "multiple-choice",
            text: "Which are states of matter?",
            choices: [
              { id: "c1", text: "Solid", isCorrect: true },
              { id: "c2", text: "Liquid", isCorrect: true },
              { id: "c3", text: "Gas", isCorrect: true },
              { id: "c4", text: "Energy", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-2-3",
            type: "descriptive",
            text: "Explain the structure of an atom.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-2-4",
            type: "single-choice",
            text: "What is the pH of a neutral solution?",
            choices: [
              { id: "c1", text: "7", isCorrect: true },
              { id: "c2", text: "0", isCorrect: false },
              { id: "c3", text: "14", isCorrect: false },
              { id: "c4", text: "5", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-2-5",
            type: "multiple-choice",
            text: "Which elements are noble gases?",
            choices: [
              { id: "c1", text: "Helium", isCorrect: true },
              { id: "c2", text: "Oxygen", isCorrect: false },
              { id: "c3", text: "Neon", isCorrect: true },
              { id: "c4", text: "Argon", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-2-6",
            type: "descriptive",
            text: "Describe the difference between ionic and covalent bonds.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-2-7",
            type: "single-choice",
            text: "What gas is used in balloons to make them float?",
            choices: [
              { id: "c1", text: "Helium", isCorrect: true },
              { id: "c2", text: "Hydrogen", isCorrect: false },
              { id: "c3", text: "Nitrogen", isCorrect: false },
              { id: "c4", text: "Oxygen", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-2-8",
            type: "multiple-choice",
            text: "Which are types of chemical reactions?",
            choices: [
              { id: "c1", text: "Synthesis", isCorrect: true },
              { id: "c2", text: "Decomposition", isCorrect: true },
              { id: "c3", text: "Evaporation", isCorrect: false },
              { id: "c4", text: "Combustion", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-2-9",
            type: "descriptive",
            text: "What is the role of catalysts in chemical reactions?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-2-10",
            type: "single-choice",
            text: "What is the chemical formula for table salt?",
            choices: [
              { id: "c1", text: "NaCl", isCorrect: true },
              { id: "c2", text: "KCl", isCorrect: false },
              { id: "c3", text: "CaCl2", isCorrect: false },
              { id: "c4", text: "MgCl2", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec2-3",
        title: "Biology Essentials",
        description: "Explore the science of life and living organisms.",
        questions: [
          {
            id: "q2-3-1",
            type: "single-choice",
            text: "What is the powerhouse of the cell?",
            choices: [
              { id: "c1", text: "Mitochondria", isCorrect: true },
              { id: "c2", text: "Nucleus", isCorrect: false },
              { id: "c3", text: "Ribosome", isCorrect: false },
              { id: "c4", text: "Golgi apparatus", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-3-2",
            type: "multiple-choice",
            text: "Which are parts of the human digestive system?",
            choices: [
              { id: "c1", text: "Stomach", isCorrect: true },
              { id: "c2", text: "Lungs", isCorrect: false },
              { id: "c3", text: "Intestines", isCorrect: true },
              { id: "c4", text: "Liver", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-3-3",
            type: "descriptive",
            text: "Explain the process of natural selection.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-3-4",
            type: "single-choice",
            text: "What is the primary function of red blood cells?",
            choices: [
              { id: "c1", text: "Carry oxygen", isCorrect: true },
              { id: "c2", text: "Fight infections", isCorrect: false },
              { id: "c3", text: "Clot blood", isCorrect: false },
              { id: "c4", text: "Digest food", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-3-5",
            type: "multiple-choice",
            text: "Which are types of ecosystems?",
            choices: [
              { id: "c1", text: "Forest", isCorrect: true },
              { id: "c2", text: "Desert", isCorrect: true },
              { id: "c3", text: "Tundra", isCorrect: true },
              { id: "c4", text: "Cloud", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-3-6",
            type: "descriptive",
            text: "Describe the role of DNA in heredity.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-3-7",
            type: "single-choice",
            text: "What is the largest organ in the human body?",
            choices: [
              { id: "c1", text: "Skin", isCorrect: true },
              { id: "c2", text: "Liver", isCorrect: false },
              { id: "c3", text: "Heart", isCorrect: false },
              { id: "c4", text: "Brain", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-3-8",
            type: "multiple-choice",
            text: "Which are types of cells?",
            choices: [
              { id: "c1", text: "Prokaryotic", isCorrect: true },
              { id: "c2", text: "Eukaryotic", isCorrect: true },
              { id: "c3", text: "Atomic", isCorrect: false },
              { id: "c4", text: "Neutrophils", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-3-9",
            type: "descriptive",
            text: "What is the significance of biodiversity?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-3-10",
            type: "single-choice",
            text: "What gas do plants release during photosynthesis?",
            choices: [
              { id: "c1", text: "Oxygen", isCorrect: true },
              { id: "c2", text: "Carbon dioxide", isCorrect: false },
              { id: "c3", text: "Nitrogen", isCorrect: false },
              { id: "c4", text: "Hydrogen", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-3-11",
            type: "multiple-choice",
            text: "Which animals are mammals?",
            choices: [
              { id: "c1", text: "Dolphin", isCorrect: true },
              { id: "c2", text: "Crocodile", isCorrect: false },
              { id: "c3", text: "Whale", isCorrect: true },
              { id: "c4", text: "Bat", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-3-12",
            type: "descriptive",
            text: "Explain the concept of homeostasis.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-3-13",
            type: "single-choice",
            text: "What is the scientific name for humans?",
            choices: [
              { id: "c1", text: "Homo sapiens", isCorrect: true },
              { id: "c2", text: "Homo erectus", isCorrect: false },
              { id: "c3", text: "Pan troglodytes", isCorrect: false },
              { id: "c4", text: "Canis lupus", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec2-4",
        title: "Environmental Science",
        description: "Study the interactions between humans and the environment.",
        questions: [
          {
            id: "q2-4-1",
            type: "single-choice",
            text: "What is the primary cause of global warming?",
            choices: [
              { id: "c1", text: "Greenhouse gases", isCorrect: true },
              { id: "c2", text: "Solar flares", isCorrect: false },
              { id: "c3", text: "Volcanic eruptions", isCorrect: false },
              { id: "c4", text: "Ocean currents", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-4-2",
            type: "multiple-choice",
            text: "Which are effects of deforestation?",
            choices: [
              { id: "c1", text: "Loss of biodiversity", isCorrect: true },
              { id: "c2", text: "Increased oxygen", isCorrect: false },
              { id: "c3", text: "Soil erosion", isCorrect: true },
              { id: "c4", text: "Climate change", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-4-3",
            type: "descriptive",
            text: "Explain the concept of the carbon cycle.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-4-4",
            type: "single-choice",
            text: "What is the main source of ocean pollution?",
            choices: [
              { id: "c1", text: "Plastic waste", isCorrect: true },
              { id: "c2", text: "Solar radiation", isCorrect: false },
              { id: "c3", text: "Tidal waves", isCorrect: false },
              { id: "c4", text: "Fish migration", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-4-5",
            type: "multiple-choice",
            text: "Which are types of pollution?",
            choices: [
              { id: "c1", text: "Air", isCorrect: true },
              { id: "c2", text: "Water", isCorrect: true },
              { id: "c3", text: "Soil", isCorrect: true },
              { id: "c4", text: "Light", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-4-6",
            type: "descriptive",
            text: "Describe the impact of climate change on ecosystems.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-4-7",
            type: "single-choice",
            text: "What is the term for species at risk of extinction?",
            choices: [
              { id: "c1", text: "Endangered", isCorrect: true },
              { id: "c2", text: "Extinct", isCorrect: false },
              { id: "c3", text: "Invasive", isCorrect: false },
              { id: "c4", text: "Migratory", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-4-8",
            type: "multiple-choice",
            text: "Which are sustainable practices?",
            choices: [
              { id: "c1", text: "Recycling", isCorrect: true },
              { id: "c2", text: "Deforestation", isCorrect: false },
              { id: "c3", text: "Renewable energy", isCorrect: true },
              { id: "c4", text: "Conservation", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-4-9",
            type: "descriptive",
            text: "What is the role of wetlands in the environment?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-4-10",
            type: "single-choice",
            text: "What is the main gas in Earth’s ozone layer?",
            choices: [
              { id: "c1", text: "Ozone", isCorrect: true },
              { id: "c2", text: "Oxygen", isCorrect: false },
              { id: "c3", text: "Nitrogen", isCorrect: false },
              { id: "c4", text: "Carbon dioxide", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec2-5",
        title: "Astronomy",
        description: "Discover the wonders of the universe.",
        questions: [
          {
            id: "q2-5-1",
            type: "single-choice",
            text: "What is the closest star to Earth?",
            choices: [
              { id: "c1", text: "Sun", isCorrect: true },
              { id: "c2", text: "Proxima Centauri", isCorrect: false },
              { id: "c3", text: "Sirius", isCorrect: false },
              { id: "c4", text: "Alpha Centauri", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-5-2",
            type: "multiple-choice",
            text: "Which are planets in our solar system?",
            choices: [
              { id: "c1", text: "Mars", isCorrect: true },
              { id: "c2", text: "Pluto", isCorrect: false },
              { id: "c3", text: "Jupiter", isCorrect: true },
              { id: "c4", text: "Saturn", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-5-3",
            type: "descriptive",
            text: "Explain the formation of stars.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-5-4",
            type: "single-choice",
            text: "What is the name of our galaxy?",
            choices: [
              { id: "c1", text: "Milky Way", isCorrect: true },
              { id: "c2", text: "Andromeda", isCorrect: false },
              { id: "c3", text: "Triangulum", isCorrect: false },
              { id: "c4", text: "Sombrero", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-5-5",
            type: "multiple-choice",
            text: "Which are types of galaxies?",
            choices: [
              { id: "c1", text: "Spiral", isCorrect: true },
              { id: "c2", text: "Elliptical", isCorrect: true },
              { id: "c3", text: "Irregular", isCorrect: true },
              { id: "c4", text: "Planetary", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-5-6",
            type: "descriptive",
            text: "Describe the significance of black holes.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-5-7",
            type: "single-choice",
            text: "What is the largest planet in our solar system?",
            choices: [
              { id: "c1", text: "Jupiter", isCorrect: true },
              { id: "c2", text: "Saturn", isCorrect: false },
              { id: "c3", text: "Neptune", isCorrect: false },
              { id: "c4", text: "Earth", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-5-8",
            type: "multiple-choice",
            text: "Which are features of the Moon?",
            choices: [
              { id: "c1", text: "Craters", isCorrect: true },
              { id: "c2", text: "Oceans", isCorrect: false },
              { id: "c3", text: "Maria", isCorrect: true },
              { id: "c4", text: "Highlands", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-5-9",
            type: "descriptive",
            text: "What is the importance of the Hubble Space Telescope?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-5-10",
            type: "single-choice",
            text: "What causes tides on Earth?",
            choices: [
              { id: "c1", text: "Moon’s gravity", isCorrect: true },
              { id: "c2", text: "Sun’s heat", isCorrect: false },
              { id: "c3", text: "Earth’s rotation", isCorrect: false },
              { id: "c4", text: "Wind", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-5-11",
            type: "multiple-choice",
            text: "Which are types of stars?",
            choices: [
              { id: "c1", text: "Red dwarf", isCorrect: true },
              { id: "c2", text: "Blue giant", isCorrect: true },
              { id: "c3", text: "White dwarf", isCorrect: true },
              { id: "c4", text: "Green star", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
        ],
      },
      {
        id: "sec2-6",
        title: "Scientific Method",
        description: "Learn the process of scientific inquiry.",
        questions: [
          {
            id: "q2-6-1",
            type: "single-choice",
            text: "What is the first step of the scientific method?",
            choices: [
              { id: "c1", text: "Ask a question", isCorrect: true },
              { id: "c2", text: "Conduct an experiment", isCorrect: false },
              { id: "c3", text: "Analyze data", isCorrect: false },
              { id: "c4", text: "Draw conclusions", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-6-2",
            type: "multiple-choice",
            text: "Which are components of a good hypothesis?",
            choices: [
              { id: "c1", text: "Testable", isCorrect: true },
              { id: "c2", text: "Falsifiable", isCorrect: true },
              { id: "c3", text: "Subjective", isCorrect: false },
              { id: "c4", text: "Specific", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-6-3",
            type: "descriptive",
            text: "Explain the importance of a control group in experiments.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-6-4",
            type: "single-choice",
            text: "What is a variable in an experiment?",
            choices: [
              { id: "c1", text: "A factor that can change", isCorrect: true },
              { id: "c2", text: "A constant value", isCorrect: false },
              { id: "c3", text: "A conclusion", isCorrect: false },
              { id: "c4", text: "A hypothesis", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-6-5",
            type: "multiple-choice",
            text: "Which are types of scientific data?",
            choices: [
              { id: "c1", text: "Quantitative", isCorrect: true },
              { id: "c2", text: "Qualitative", isCorrect: true },
              { id: "c3", text: "Hypothetical", isCorrect: false },
              { id: "c4", text: "Numerical", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-6-6",
            type: "descriptive",
            text: "Describe the role of peer review in science.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-6-7",
            type: "single-choice",
            text: "What is a theory in science?",
            choices: [
              { id: "c1", text: "A well-substantiated explanation", isCorrect: true },
              { id: "c2", text: "A guess", isCorrect: false },
              { id: "c3", text: "A hypothesis", isCorrect: false },
              { id: "c4", text: "A law", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q2-6-8",
            type: "multiple-choice",
            text: "Which are steps in the scientific method?",
            choices: [
              { id: "c1", text: "Form a hypothesis", isCorrect: true },
              { id: "c2", text: "Conduct an experiment", isCorrect: true },
              { id: "c3", text: "Analyze results", isCorrect: true },
              { id: "c4", text: "Write a story", isCorrect: false },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q2-6-9",
            type: "descriptive",
            text: "What is the importance of reproducibility in science?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q2-6-10",
            type: "single-choice",
            text: "What is a scientific law?",
            choices: [
              { id: "c1", text: "A statement of observed patterns", isCorrect: true },
              { id: "c2", text: "A hypothesis", isCorrect: false },
              { id: "c3", text: "An experiment", isCorrect: false },
              { id: "c4", text: "A theory", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
    ],
  },
  {
    id: "course3",
    title: "Literature and Culture",
    description: "Immerse yourself in the rich tapestry of classic and modern literature with this course, designed to explore their profound cultural impact. Study timeless works from authors like Shakespeare and Austen, alongside contemporary masterpieces that shape global perspectives. Through in-depth quizzes and analytical questions, examine themes, historical contexts, and societal influences embedded in literature. This course covers epic poetry, novels, and cultural narratives, offering insights into how stories reflect and shape human experiences across diverse cultures and eras.",
    isPublished: true,
    isMyCourse: false,
    author: {
          name: "Aisha Khan",
          avatar: `${placeholderImageURL}2`,
          initials: getInitials("Aisha Khan"),
        },
    sections: [
      {
        id: "sec3-1",
        title: "Classic Literature",
        description: "Study timeless works of literature.",
        questions: [
          {
            id: "q3-1-1",
            type: "single-choice",
            text: "Who wrote 'Moby-Dick'?",
            choices: [
              { id: "c1", text: "Herman Melville", isCorrect: true },
              { id: "c2", text: "Mark Twain", isCorrect: false },
              { id: "c3", text: "Nathaniel Hawthorne", isCorrect: false },
              { id: "c4", text: "Edgar Allan Poe", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q3-1-2",
            type: "multiple-choice",
            text: "Which are works by Charles Dickens?",
            choices: [
              { id: "c1", text: "Great Expectations", isCorrect: true },
              { id: "c2", text: "Jane Eyre", isCorrect: false },
              { id: "c3", text: "Oliver Twist", isCorrect: true },
              { id: "c4", text: "A Tale of Two Cities", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q3-1-3",
            type: "descriptive",
            text: "Explain the themes in 'Pride and Prejudice'.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q3-1-4",
            type: "single-choice",
            text: "Who wrote 'The Odyssey'?",
            choices: [
              { id: "c1", text: "Homer", isCorrect: true },
              { id: "c2", text: "Virgil", isCorrect: false },
              { id: "c3", text: "Sophocles", isCorrect: false },
              { id: "c4", text: "Aristotle", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q3-1-5",
            type: "multiple-choice",
            text: "Which are Shakespearean tragedies?",
            choices: [
              { id: "c1", text: "Romeo and Juliet", isCorrect: true },
              { id: "c2", text: "A Midsummer Night’s Dream", isCorrect: false },
              { id: "c3", text: "Macbeth", isCorrect: true },
              { id: "c4", text: "King Lear", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q3-1-6",
            type: "descriptive",
            text: "Describe the role of satire in 'Gulliver’s Travels'.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q3-1-7",
            type: "single-choice",
            text: "Who wrote 'Crime and Punishment'?",
            choices: [
              { id: "c1", text: "Fyodor Dostoevsky", isCorrect: true },
              { id: "c2", text: "Leo Tolstoy", isCorrect: false },
              { id: "c3", text: "Anton Chekhov", isCorrect: false },
              { id: "c4", text: "Nikolai Gogol", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q3-1-8",
            type: "multiple-choice",
            text: "Which are epic poems?",
            choices: [
              { id: "c1", text: "The Iliad", isCorrect: true },
              { id: "c2", text: "Paradise Lost", isCorrect: true },
              { id: "c3", text: "The Raven", isCorrect: false },
              { id: "c4", text: "Beowulf", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q3-1-9",
            type: "descriptive",
            text: "What is the significance of 'Don Quixote' in literature?",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q3-1-10",
            type: "single-choice",
            text: "Who wrote 'Frankenstein'?",
            choices: [
              { id: "c1", text: "Mary Shelley", isCorrect: true },
              { id: "c2", text: "Bram Stoker", isCorrect: false },
              { id: "c3", text: "Emily Brontë", isCorrect: false },
              { id: "c4", text: "Charlotte Brontë", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ],
      },
      {
        id: "sec3-2",
        title: "Modern Literature",
        description: "Explore literature from the 20th and 21st centuries.",
        questions: [
          {
            id: "q3-2-1",
            type: "single-choice",
            text: "Who wrote '1984'?",
            choices: [
              { id: "c1", text: "George Orwell", isCorrect: true },
              { id: "c2", text: "Aldous Huxley", isCorrect: false },
              { id: "c3", text: "Ray Bradbury", isCorrect: false },
              { id: "c4", text: "Philip K. Dick", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
          {
            id: "q3-2-2",
            type: "multiple-choice",
            text: "Which are novels by Toni Morrison?",
            choices: [
              { id: "c1", text: "Beloved", isCorrect: true },
              { id: "c2", text: "Their Eyes Were Watching God", isCorrect: false },
              { id: "c3", text: "Song of Solomon", isCorrect: true },
              { id: "c4", text: "Jazz", isCorrect: true },
            ],
            score: 15,
            timeLimit: 45,
            required: true,
          },
          {
            id: "q3-2-3",
            type: "descriptive",
            text: "Explain the themes in 'The Great Gatsby'.",
            choices: [],
            score: 20,
            timeLimit: 120,
            required: false,
          },
          {
            id: "q3-2-4",
            type: "single-choice",
            text: "Who wrote 'To Kill a Mockingbird'?",
            choices: [
              { id: "c1", text: "Harper Lee", isCorrect: true },
              { id: "c2", text: "John Steinbeck", isCorrect: false },
              { id: "c3", text: "Ernest Hemingway", isCorrect: false },
              { id: "c4", text: "William Faulkner", isCorrect: false },
            ],
            score: 10,
            timeLimit: 30,
            required: true,
          },
        ]
      }
    ]
  }
]
