import { Section } from "@/types";

export const quizData: Section[] = [
  {
    id: "sec1",
    title: "General Knowledge",
    description: "Test your knowledge on various topics.",
    questions: [
      {
        id: "q1",
        type: "single-choice",
        text: "What is the capital city of France?",
        choices: [
          { id: "c1", text: "Paris", isCorrect: true },
          { id: "c2", text: "London", isCorrect: false },
          { id: "c3", text: "Berlin", isCorrect: false },
          { id: "c4", text: "Madrid", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q2",
        type: "multiple-choice",
        text: "Which of these are planets in our solar system?",
        choices: [
          { id: "c1", text: "Jupiter", isCorrect: true },
          { id: "c2", text: "Pluto", isCorrect: false },
          { id: "c3", text: "Mars", isCorrect: true },
          { id: "c4", text: "Sun", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q3",
        type: "descriptive",
        text: "Describe the process of photosynthesis in plants.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q4",
        type: "single-choice",
        text: "Who painted the Mona Lisa?",
        choices: [
          { id: "c1", text: "Leonardo da Vinci", isCorrect: true },
          { id: "c2", text: "Vincent van Gogh", isCorrect: false },
          { id: "c3", text: "Pablo Picasso", isCorrect: false },
          { id: "c4", text: "Claude Monet", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q5",
        type: "multiple-choice",
        text: "Which of these are programming languages?",
        choices: [
          { id: "c1", text: "Python", isCorrect: true },
          { id: "c2", text: "HTML", isCorrect: false },
          { id: "c3", text: "Java", isCorrect: true },
          { id: "c4", text: "CSS", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q6",
        type: "descriptive",
        text: "Explain the significance of the Industrial Revolution.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q7",
        type: "single-choice",
        text: "What is the largest mammal on Earth?",
        choices: [
          { id: "c1", text: "Blue Whale", isCorrect: true },
          { id: "c2", text: "African Elephant", isCorrect: false },
          { id: "c3", text: "Giraffe", isCorrect: false },
          { id: "c4", text: "Polar Bear", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q8",
        type: "multiple-choice",
        text: "Which countries are in South America?",
        choices: [
          { id: "c1", text: "Brazil", isCorrect: true },
          { id: "c2", text: "Canada", isCorrect: false },
          { id: "c3", text: "Argentina", isCorrect: true },
          { id: "c4", text: "India", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q9",
        type: "descriptive",
        text: "What are the main causes of climate change?",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q10",
        type: "single-choice",
        text: "What is the chemical symbol for gold?",
        choices: [
          { id: "c1", text: "Au", isCorrect: true },
          { id: "c2", text: "Ag", isCorrect: false },
          { id: "c3", text: "Fe", isCorrect: false },
          { id: "c4", text: "Cu", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
    ],
  },
  {
    id: "sec2",
    title: "Science and Technology",
    questions: [
      {
        id: "q11",
        type: "single-choice",
        text: "What gas do plants absorb from the atmosphere?",
        choices: [
          { id: "c1", text: "Carbon Dioxide", isCorrect: true },
          { id: "c2", text: "Oxygen", isCorrect: false },
          { id: "c3", text: "Nitrogen", isCorrect: false },
          { id: "c4", text: "Helium", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q12",
        type: "multiple-choice",
        text: "Which of these are renewable energy sources?",
        choices: [
          { id: "c1", text: "Solar", isCorrect: true },
          { id: "c2", text: "Coal", isCorrect: false },
          { id: "c3", text: "Wind", isCorrect: true },
          { id: "c4", text: "Natural Gas", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q13",
        type: "descriptive",
        text: "Explain how a vaccine works to protect against diseases.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q14",
        type: "single-choice",
        text: "Who invented the telephone?",
        choices: [
          { id: "c1", text: "Alexander Graham Bell", isCorrect: true },
          { id: "c2", text: "Thomas Edison", isCorrect: false },
          { id: "c3", text: "Nikola Tesla", isCorrect: false },
          { id: "c4", text: "Guglielmo Marconi", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q15",
        type: "multiple-choice",
        text: "Which elements are noble gases?",
        choices: [
          { id: "c1", text: "Helium", isCorrect: true },
          { id: "c2", text: "Oxygen", isCorrect: false },
          { id: "c3", text: "Neon", isCorrect: true },
          { id: "c4", text: "Nitrogen", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q16",
        type: "descriptive",
        text: "Describe the function of DNA in living organisms.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q17",
        type: "single-choice",
        text: "What is the primary source of energy for Earth's climate system?",
        choices: [
          { id: "c1", text: "Sun", isCorrect: true },
          { id: "c2", text: "Moon", isCorrect: false },
          { id: "c3", text: "Geothermal Heat", isCorrect: false },
          { id: "c4", text: "Ocean Currents", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q18",
        type: "multiple-choice",
        text: "Which of these are types of computer memory?",
        choices: [
          { id: "c1", text: "RAM", isCorrect: true },
          { id: "c2", text: "CPU", isCorrect: false },
          { id: "c3", text: "ROM", isCorrect: true },
          { id: "c4", text: "GPU", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q19",
        type: "descriptive",
        text: "What is the significance of quantum computing?",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q20",
        type: "single-choice",
        text: "What is the unit of electric current?",
        choices: [
          { id: "c1", text: "Ampere", isCorrect: true },
          { id: "c2", text: "Volt", isCorrect: false },
          { id: "c3", text: "Watt", isCorrect: false },
          { id: "c4", text: "Ohm", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
    ],
  },
  {
    id: "sec3",
    title: "History",
    description: "Explore events that shaped the world.",
    questions: [
      {
        id: "q21",
        type: "single-choice",
        text: "Who was the first president of the United States?",
        choices: [
          { id: "c1", text: "George Washington", isCorrect: true },
          { id: "c2", text: "Thomas Jefferson", isCorrect: false },
          { id: "c3", text: "Abraham Lincoln", isCorrect: false },
          { id: "c4", text: "John Adams", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q22",
        type: "multiple-choice",
        text: "Which events occurred during World War II?",
        choices: [
          { id: "c1", text: "Attack on Pearl Harbor", isCorrect: true },
          { id: "c2", text: "American Revolution", isCorrect: false },
          { id: "c3", text: "D-Day Invasion", isCorrect: true },
          { id: "c4", text: "Fall of the Berlin Wall", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q23",
        type: "descriptive",
        text: "Describe the impact of the Renaissance on European culture.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q24",
        type: "single-choice",
        text: "In which year did the Titanic sink?",
        choices: [
          { id: "c1", text: "1912", isCorrect: true },
          { id: "c2", text: "1905", isCorrect: false },
          { id: "c3", text: "1920", isCorrect: false },
          { id: "c4", text: "1898", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q25",
        type: "multiple-choice",
        text: "Which civilizations built pyramids?",
        choices: [
          { id: "c1", text: "Egyptian", isCorrect: true },
          { id: "c2", text: "Roman", isCorrect: false },
          { id: "c3", text: "Mayan", isCorrect: true },
          { id: "c4", text: "Greek", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q26",
        type: "descriptive",
        text: "Explain the causes of the French Revolution.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q27",
        type: "single-choice",
        text: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
        choices: [
          { id: "c1", text: "Nikita Khrushchev", isCorrect: true },
          { id: "c2", text: "Joseph Stalin", isCorrect: false },
          { id: "c3", text: "Vladimir Lenin", isCorrect: false },
          { id: "c4", text: "Mikhail Gorbachev", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q28",
        type: "multiple-choice",
        text: "Which of these were ancient wonders of the world?",
        choices: [
          { id: "c1", text: "Hanging Gardens of Babylon", isCorrect: true },
          { id: "c2", text: "Eiffel Tower", isCorrect: false },
          { id: "c3", text: "Great Pyramid of Giza", isCorrect: true },
          { id: "c4", text: "Statue of Liberty", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q29",
        type: "descriptive",
        text: "What was the significance of the Magna Carta?",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q30",
        type: "single-choice",
        text: "Which empire was ruled by Genghis Khan?",
        choices: [
          { id: "c1", text: "Mongol Empire", isCorrect: true },
          { id: "c2", text: "Roman Empire", isCorrect: false },
          { id: "c3", text: "Ottoman Empire", isCorrect: false },
          { id: "c4", text: "Byzantine Empire", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
    ],
  },
  {
    id: "sec4",
    title: "Literature and Arts",
    questions: [
      {
        id: "q31",
        type: "single-choice",
        text: "Who wrote 'Pride and Prejudice'?",
        choices: [
          { id: "c1", text: "Jane Austen", isCorrect: true },
          { id: "c2", text: "Charlotte Brontë", isCorrect: false },
          { id: "c3", text: "Emily Dickinson", isCorrect: false },
          { id: "c4", text: "Mary Shelley", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q32",
        type: "multiple-choice",
        text: "Which of these are plays by William Shakespeare?",
        choices: [
          { id: "c1", text: "Hamlet", isCorrect: true },
          { id: "c2", text: "Faust", isCorrect: false },
          { id: "c3", text: "Macbeth", isCorrect: true },
          { id: "c4", text: "Don Quixote", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q33",
        type: "descriptive",
        text: "Describe the characteristics of Romanticism in literature.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q34",
        type: "single-choice",
        text: "Which artist is known for the painting 'Starry Night'?",
        choices: [
          { id: "c1", text: "Vincent van Gogh", isCorrect: true },
          { id: "c2", text: "Claude Monet", isCorrect: false },
          { id: "c3", text: "Pablo Picasso", isCorrect: false },
          { id: "c4", text: "Rembrandt", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q35",
        type: "multiple-choice",
        text: "Which of these are musical instruments?",
        choices: [
          { id: "c1", text: "Violin", isCorrect: true },
          { id: "c2", text: "Trombone", isCorrect: true },
          { id: "c3", text: "Saxophone", isCorrect: true },
          { id: "c4", text: "Microphone", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q36",
        type: "descriptive",
        text: "Explain the influence of Impressionism on modern art.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q37",
        type: "single-choice",
        text: "Who wrote the novel '1984'?",
        choices: [
          { id: "c1", text: "George Orwell", isCorrect: true },
          { id: "c2", text: "Aldous Huxley", isCorrect: false },
          { id: "c3", text: "Ray Bradbury", isCorrect: false },
          { id: "c4", text: "J.R.R. Tolkien", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q38",
        type: "multiple-choice",
        text: "Which of these are film genres?",
        choices: [
          { id: "c1", text: "Comedy", isCorrect: true },
          { id: "c2", text: "Romance", isCorrect: true },
          { id: "c3", text: "Documentary", isCorrect: true },
          { id: "c4", text: "Novel", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q39",
        type: "descriptive",
        text: "What is the significance of Greek mythology in Western literature?",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q40",
        type: "single-choice",
        text: "Which composer wrote 'Symphony No. 9'?",
        choices: [
          { id: "c1", text: "Ludwig van Beethoven", isCorrect: true },
          { id: "c2", text: "Wolfgang Amadeus Mozart", isCorrect: false },
          { id: "c3", text: "Johann Sebastian Bach", isCorrect: false },
          { id: "c4", text: "Franz Schubert", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
    ],
  },
  {
    id: "sec5",
    title: "Geography",
    questions: [
      {
        id: "q41",
        type: "single-choice",
        text: "What is the longest river in the world?",
        choices: [
          { id: "c1", text: "Nile", isCorrect: true },
          { id: "c2", text: "Amazon", isCorrect: false },
          { id: "c3", text: "Yangtze", isCorrect: false },
          { id: "c4", text: "Mississippi", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q42",
        type: "multiple-choice",
        text: "Which countries border the Mediterranean Sea?",
        choices: [
          { id: "c1", text: "Spain", isCorrect: true },
          { id: "c2", text: "Brazil", isCorrect: false },
          { id: "c3", text: "Italy", isCorrect: true },
          { id: "c4", text: "Japan", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q43",
        type: "descriptive",
        text: "Explain the formation of the Himalayan mountain range.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q44",
        type: "single-choice",
        text: "What is the capital of Australia?",
        choices: [
          { id: "c1", text: "Canberra", isCorrect: true },
          { id: "c2", text: "Sydney", isCorrect: false },
          { id: "c3", text: "Melbourne", isCorrect: false },
          { id: "c4", text: "Perth", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q45",
        type: "multiple-choice",
        text: "Which of these are deserts?",
        choices: [
          { id: "c1", text: "Sahara", isCorrect: true },
          { id: "c2", text: "Amazon", isCorrect: false },
          { id: "c3", text: "Gobi", isCorrect: true },
          { id: "c4", text: "Arctic", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q46",
        type: "descriptive",
        text: "Describe the impact of deforestation on global ecosystems.",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q47",
        type: "single-choice",
        text: "Which continent is the smallest by land area?",
        choices: [
          { id: "c1", text: "Australia", isCorrect: true },
          { id: "c2", text: "Antarctica", isCorrect: false },
          { id: "c3", text: "Asia", isCorrect: false },
          { id: "c4", text: "Africa", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
      {
        id: "q48",
        type: "multiple-choice",
        text: "Which of these are volcanic mountains?",
        choices: [
          { id: "c1", text: "Mount Vesuvius", isCorrect: true },
          { id: "c2", text: "Mount Everest", isCorrect: false },
          { id: "c3", text: "Mount Fuji", isCorrect: true },
          { id: "c4", text: "Mount Rushmore", isCorrect: false },
        ],
        score: 15,
        timeLimit: 45,
        required: true,
      },
      {
        id: "q49",
        type: "descriptive",
        text: "What are the major factors influencing ocean currents?",
        choices: [],
        score: 20,
        timeLimit: 120,
        required: false,
      },
      {
        id: "q50",
        type: "single-choice",
        text: "What is the highest mountain in the world?",
        choices: [
          { id: "c1", text: "Mount Everest", isCorrect: true },
          { id: "c2", text: "K2", isCorrect: false },
          { id: "c3", text: "Kangchenjunga", isCorrect: false },
          { id: "c4", text: "Lhotse", isCorrect: false },
        ],
        score: 10,
        timeLimit: 30,
        required: true,
      },
    ],
  },
];